logging:
  level: "DEBUG"

auth:
  access_token_ttl: 900
  refresh_token_ttl: 60400

database:
  host: db
  port: 5432
  user: messenger_user
  password: "messenger_password_123"
  database: messenger_database

redis:
  url: "redis://redis:6379/0"
